"""Regenerate the ROTBOSON residual and Jacobian C kernels from SymPy.

This is the Phase 4 code generator.  It derives the Einstein--Klein--Gordon
system symbolically (:mod:`sympy_system`), differentiates it to form the
Jacobian, and emits clean C for the kernels that were previously generated by a
Mathematica script and pasted by hand:

* ``src/rhs_vars.c`` / ``src/rhs_vars.h``  -- interior + boundary residuals
* ``src/csr_vars.c`` / ``src/csr_vars.h``  -- Jacobian stencil kernels

The generated files are checked in.  A test re-runs this generator and asserts
the output is byte-identical to the checked-in files, and an MMS test verifies
the emitted kernels recover a manufactured solution at the design order.

Usage:
    uv run tools/generate_kernels.py [--check] [--out-dir DIR]
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

import sympy as sp
import sympy_system as ss

# ---------------------------------------------------------------------------
# Finite-difference stencil data (offsets + per-subtype coefficients).
#
# Each stencil maps a grid point offset (dr_off, dz_off) to the 5 subtype
# coefficients [value, dRu, dZu, dRRu, dZZu].  The coefficient strings are the
# step-scaled Fornberg weights (see src/derivatives.c, Fornberg-validated in
# Phase 3).  Subtype order matches csr_vars.c: value, dr*Dr, dz*Dz, dr^2*Drr,
# dz^2*Dzz.
# ---------------------------------------------------------------------------

FD_2ND = {
    "D_2_10": "-0.5",
    "D_2_11": "+0.0",
    "D_2_12": "+0.5",
    "D_2_20": "+1.0",
    "D_2_21": "-2.0",
    "D_2_22": "+1.0",
}

FD_4TH = {
    "D10": "+1.0 / 12.0",
    "D11": "-2.0 / 3.0",
    "D12": "+0.0",
    "D13": "+2.0 / 3.0",
    "D14": "-1.0 / 12.0",
    "D20": "-1.0 / 12.0",
    "D21": "+4.0 / 3.0",
    "D22": "-2.5",
    "D23": "+4.0 / 3.0",
    "D24": "-1.0 / 12.0",
    "S10": "+0.0",
    "S11": "-1.0 / 12.0",
    "S12": "+0.5",
    "S13": "-1.5",
    "S14": "+5.0 / 6.0",
    "S15": "+0.25",
    "S20": "+1.0 / 12.0",
    "S21": "-0.5",
    "S22": "+7.0 / 6.0",
    "S23": "-1.0 / 3.0",
    "S24": "-1.25",
    "S25": "+5.0 / 6.0",
}


def _stencil(offsets, coeffs, ghost):
    """Normalize a stencil spec: list of (dr_off, dz_off, [5 coeff strings])."""
    return {"ghost": ghost, "points": list(zip(offsets, coeffs, strict=True))}


# 2nd-order centered-centered (5 points).
STENCILS_2ND = {
    "cc": _stencil(
        [(-1, 0), (0, -1), (0, 0), (0, 1), (1, 0)],
        [
            ["0.0", "D_2_10", "0.0", "D_2_20", "0.0"],
            ["0.0", "0.0", "D_2_10", "0.0", "D_2_20"],
            ["1.0", "0.0", "0.0", "D_2_21", "D_2_21"],
            ["0.0", "0.0", "D_2_12", "0.0", "D_2_22"],
            ["0.0", "D_2_12", "0.0", "D_2_22", "0.0"],
        ],
        ghost=1,
    )
}

# 4th-order stencils (centered-centered and semi-onesided variants).
STENCILS_4TH = {
    "cc": _stencil(
        [(-2, 0), (-1, 0), (0, -2), (0, -1), (0, 0), (0, 1), (0, 2), (1, 0), (2, 0)],
        [
            ["0.0", "D10", "0.0", "D20", "0.0"],
            ["0.0", "D11", "0.0", "D21", "0.0"],
            ["0.0", "0.0", "D10", "0.0", "D20"],
            ["0.0", "0.0", "D11", "0.0", "D21"],
            ["1.0", "0.0", "0.0", "D22", "D22"],
            ["0.0", "0.0", "D13", "0.0", "D23"],
            ["0.0", "0.0", "D14", "0.0", "D24"],
            ["0.0", "D13", "0.0", "D23", "0.0"],
            ["0.0", "D14", "0.0", "D24", "0.0"],
        ],
        ghost=2,
    ),
    "cs": _stencil(
        [(-2, 0), (-1, 0), (0, -4), (0, -3), (0, -2), (0, -1), (0, 0), (0, 1), (1, 0), (2, 0)],
        [
            ["0.0", "D10", "0.0", "D20", "0.0"],
            ["0.0", "D11", "0.0", "D21", "0.0"],
            ["0.0", "0.0", "0.0", "0.0", "S20"],
            ["0.0", "0.0", "S11", "0.0", "S21"],
            ["0.0", "0.0", "S12", "0.0", "S22"],
            ["0.0", "0.0", "S13", "0.0", "S23"],
            ["1.0", "0.0", "S14", "D22", "S24"],
            ["0.0", "0.0", "S15", "0.0", "S25"],
            ["0.0", "D13", "0.0", "D23", "0.0"],
            ["0.0", "D14", "0.0", "D24", "0.0"],
        ],
        ghost=2,
    ),
    "sc": _stencil(
        [(-4, 0), (-3, 0), (-2, 0), (-1, 0), (0, -2), (0, -1), (0, 0), (0, 1), (0, 2), (1, 0)],
        [
            ["0.0", "0.0", "0.0", "S20", "0.0"],
            ["0.0", "S11", "0.0", "S21", "0.0"],
            ["0.0", "S12", "0.0", "S22", "0.0"],
            ["0.0", "S13", "0.0", "S23", "0.0"],
            ["0.0", "0.0", "D10", "0.0", "D20"],
            ["0.0", "0.0", "D11", "0.0", "D21"],
            ["1.0", "S14", "0.0", "S24", "D22"],
            ["0.0", "0.0", "D13", "0.0", "D23"],
            ["0.0", "0.0", "D14", "0.0", "D24"],
            ["0.0", "S15", "0.0", "S25", "0.0"],
        ],
        ghost=2,
    ),
    "ss": _stencil(
        [
            (-4, 0),
            (-3, 0),
            (-2, 0),
            (-1, 0),
            (0, -4),
            (0, -3),
            (0, -2),
            (0, -1),
            (0, 0),
            (0, 1),
            (1, 0),
        ],
        [
            ["0.0", "0.0", "0.0", "S20", "0.0"],
            ["0.0", "S11", "0.0", "S21", "0.0"],
            ["0.0", "S12", "0.0", "S22", "0.0"],
            ["0.0", "S13", "0.0", "S23", "0.0"],
            ["0.0", "0.0", "0.0", "0.0", "S20"],
            ["0.0", "0.0", "S11", "0.0", "S21"],
            ["0.0", "0.0", "S12", "0.0", "S22"],
            ["0.0", "0.0", "S13", "0.0", "S23"],
            ["1.0", "S14", "S14", "S24", "S24"],
            ["0.0", "0.0", "S15", "0.0", "S25"],
            ["0.0", "S15", "0.0", "S25", "0.0"],
        ],
        ghost=2,
    ),
}

# Which finite-difference quantities are materialized as locals (only those
# referenced by the Jacobian expressions; the rest are handled via the stencil
# coefficients in the CSR write-out).
FD_USED = {"dRu": (1, 2, 3, 5, 6), "dZu": (1, 2, 3, 5, 6), "dRRu": (1, 3)}

# Grid-function physical names, for the readability declarations.
GRID_NAME = {1: "u1", 2: "u2", 3: "u3", 4: "u4", 5: "u5", 6: "u6"}


def _param_name(g, dr_off, dz_off, dr_min, dz_min):
    return f"u{g}{dr_off - dr_min}{dz_off - dz_min}"


def _index_str(dr_off, dz_off):
    def off(axis, o):
        if o == 0:
            return axis
        return f"{axis} {'+' if o > 0 else '-'} {abs(o)}"

    return f"IDX({off('i', dr_off)}, {off('j', dz_off)})"


def _signature(fname, stencil, used_params=None):
    """Emit the function signature.  ``used_params`` is a set of parameter
    names referenced by the body; unused grid-value parameters are declared
    anonymous (no name) so the compiler does not warn about them."""
    dr_min = min(p[0][0] for p in stencil["points"])
    dz_min = min(p[0][1] for p in stencil["points"])
    used = used_params if used_params is not None else set()

    def named(name):
        return name if name in used else ""

    lines = [f"void {fname}("]
    lines.append("\tdouble *aa, MKL_INT *ia, MKL_INT *ja,")
    lines.append(
        "\tconst MKL_INT NrTotal, const MKL_INT NzTotal, const MKL_INT dim, const MKL_INT ghost,"
    )
    lines.append("\tconst MKL_INT i, const MKL_INT j, const double dr, const double dz,")
    lines.append("\tconst MKL_INT l, const double m, const double xi,")
    for g in range(1, 7):
        params = []
        for (dr_off, dz_off), _ in stencil["points"]:
            p = _param_name(g, dr_off, dz_off, dr_min, dz_min)
            nm = named(p)
            params.append(f"const double {nm}".rstrip())
        lines.append("\t" + ", ".join(params) + ",")
    lines.append("\tconst MKL_INT offset1, const MKL_INT offset2, const MKL_INT offset3,")
    lines.append("\tconst MKL_INT offset4, const MKL_INT offset5, const MKL_INT offset6)")
    return "\n".join(lines)


def _decl_block(stencil):
    """Grid-value + physical-variable declarations shared by every kernel."""
    dr_min = min(p[0][0] for p in stencil["points"])
    dz_min = min(p[0][1] for p in stencil["points"])
    center = {g: _param_name(g, 0, 0, dr_min, dz_min) for g in range(1, 7)}
    return "\n".join(
        [
            "\t// Grid values at the stencil centre (u1=log alpha, u2=beta,",
            "\t// u3=log h, u4=log a, u5=psi, u6=lambda).",
            f"\tdouble u1 = {center[1]};",
            f"\tdouble u2 = {center[2]};",
            f"\tdouble u3 = {center[3]};",
            f"\tdouble u4 = {center[4]};",
            f"\tdouble u5 = {center[5]};",
            f"\tdouble u6 = {center[6]};",
            "",
            "\t// Physical names for readability.",
            "\tdouble alpha = exp(u1);",
            "\tdouble h = exp(u3);",
            "\tdouble a = exp(u4);",
            "\tdouble psi = u5;",
            "\tdouble lambda = u6;",
            "",
            "\t// Coordinates and step ratios.",
            "\tdouble ri = (double)i + 0.5 - ghost;",
            "\tdouble r = ri * dr;",
            "\tdouble dzodr = dz / dr;",
            "\tdouble drodz = dr / dz;",
            "\tdouble dr2 = dr * dr;",
            "",
            "\t// Scalar field frequency and mass.",
            "\tdouble w = omega_calc(xi, m);",
            "\tdouble m2 = m * m;",
            "\tMKL_INT w_idx = GNUM * dim;",
            "",
            "\t// Scalar field short-hands (phi = r^l * psi).",
            "\tdouble rlm1 = (l == 1) ? 1.0 : pow(r, l - 1);",
            "\tdouble rl = rlm1 * r;",
            "\tdouble phior = rlm1 * psi;",
            "\tdouble phi = r * phior;",
            "\tdouble phi2or2 = phior * phior;",
            "\tdouble phi2 = phi * phi;",
            "\tdouble wplOmega = w + l * u2;",
            "",
            "\t// Squared variables.",
            "\tdouble alpha2 = alpha * alpha;",
            "\tdouble h2 = h * h;",
            "\tdouble a2 = a * a;",
        ]
    )


def _fd_block(stencil):
    """Emit the materialized finite-difference locals from the stencil."""
    dr_min = min(p[0][0] for p in stencil["points"])
    dz_min = min(p[0][1] for p in stencil["points"])
    lines = ["\t// Finite differences (step-scaled Fornberg stencils)."]
    for var, idxs in FD_USED.items():
        col = {"dRu": 1, "dZu": 2, "dRRu": 3}[var]
        for k in idxs:
            terms = []
            for (dr_off, dz_off), coeffs in stencil["points"]:
                c = coeffs[col]
                if c == "0.0":
                    continue
                p = _param_name(k, dr_off, dz_off, dr_min, dz_min)
                terms.append(f"{c} * {p}")
            lines.append(f"\tdouble {var}{k} = " + " + ".join(terms) + ";")
    return "\n".join(lines)


def _submatrix_decls():
    lines = [
        "\t// Jacobian submatrices: one 5-entry row per grid function,",
        "\t// plus the omega (frequency) entry.",
    ]
    for k in range(1, 7):
        lines.append(f"\tdouble jacobian_submatrix_{k}[5] = {{ 0.0 }};")
    lines.append("\tdouble jacobian_submatrix_w = 0.0;")
    return "\n".join(lines)


def _emit_rhs(jac_row, row_idx):
    """Emit the submatrix assignments for one residual equation (grid number)."""
    lines = []
    lines.append(f"\t// Jacobian of residual {row_idx} w.r.t. each grid function.")
    for g in range(1, 7):
        lines.append(f"\t//   submatrix {g} = [u, dRu, dZu, dRRu, dZZu].")
        for k in range(5):
            expr = jac_row[5 * (g - 1) + k]
            lines.append(f"\tjacobian_submatrix_{g}[{k}] = {expr};")
    w = jac_row[-1]
    lines.append("\t// Omega term (chain rule dw/dxi is applied at run time).")
    lines.append(f"\tjacobian_submatrix_w = dw_du(xi, m) * ({w});")
    return "\n".join(lines)


def _emit_csr(stencil, jac_row, row_idx):
    """Emit the CSR write-out for one residual equation."""
    off = row_idx  # offsetN variable is 1-based
    lines = []
    lines.append(f"\t// Row {row_idx - 1} * dim + IDX(i, j) starts at offset{off}.")
    lines.append(f"\tia[{row_idx - 1} * dim + IDX(i, j)] = BASE + offset{off};")
    lines.append("")
    lines.append("\t// Values.")
    n = 0
    for g in range(1, 7):
        for (_, _), coeffs in stencil["points"]:
            terms = []
            for k, c in enumerate(coeffs):
                if c == "0.0":
                    continue
                if jac_row[5 * (g - 1) + k] == "0":
                    continue
                terms.append(f"+{c}*jacobian_submatrix_{g}[{k}]")
            if terms:
                lines.append(f"\taa[offset{off} + {n:3d}] = " + "".join(terms) + ";")
                n += 1
    # omega term
    if jac_row[-1] != "0":
        lines.append(f"\taa[offset{off} + {n:3d}] = jacobian_submatrix_w;")
        n += 1
    lines.append("")
    lines.append("\t// Columns.")
    n = 0
    for g in range(1, 7):
        for (dr_off, dz_off), coeffs in stencil["points"]:
            terms = []
            for k, c in enumerate(coeffs):
                if c == "0.0":
                    continue
                if jac_row[5 * (g - 1) + k] == "0":
                    continue
                terms.append(f"+{c}*jacobian_submatrix_{g}[{k}]")
            if terms:
                lines.append(
                    f"\tja[offset{off} + {n:3d}] = BASE + {g - 1} * dim + "
                    f"{_index_str(dr_off, dz_off)};"
                )
                n += 1
    if jac_row[-1] != "0":
        lines.append(f"\tja[offset{off} + {n:3d}] = BASE + w_idx;")
    return "\n".join(lines)


def _function_body(fname, stencil, jac):
    body = ["\t(void)NrTotal;"]  # NrTotal is redundant (dim = NrTotal * NzTotal)
    body.append("")
    body.append(_decl_block(stencil))
    body.append("")
    body.append(_fd_block(stencil))
    body.append("")
    body.append(_submatrix_decls())
    for row_idx in range(1, 7):
        body.append("")
        body.append(f"\t// CSR CODE FOR GRID NUMBER {row_idx} (residual {row_idx - 1}).")
        body.append("")
        body.append(_emit_rhs(jac[row_idx - 1], row_idx))
        body.append("")
        body.append(_emit_csr(stencil, jac[row_idx - 1], row_idx))
    body.append("")
    body.append("\treturn;")
    body_text = "\n".join(body)
    # Parameters referenced by name in the body (grid values via the FD
    # stencils and the centre assignment).  Unused ones are declared
    # anonymous so the compiler does not warn (backlog item #7).
    used = set(re.findall(r"\bu\d\d\d\b", body_text))
    return _signature(fname, stencil, used) + "\n{\n" + body_text + "\n}"


# ---------------------------------------------------------------------------
# C expression printing
# ---------------------------------------------------------------------------


def _ccode(expr):
    # sympy ccode already emits M_PI and pow(); drop the redundant `1.0*`.
    return sp.ccode(expr, user_functions={})


def _expr_strings(jac):
    """Convert the 6x31 sympy Jacobian to 6x31 C strings (zero -> '0')."""
    out = []
    for row in jac:
        r = []
        for e in row:
            if e == 0:
                r.append("0")
            else:
                s = _ccode(e)
                s = s.replace("1.0*", "").replace("*(1.0", "*(")
                r.append(s)
        out.append(r)
    return out


# ---------------------------------------------------------------------------
# File emitters
# ---------------------------------------------------------------------------

_HEADER = """\
// Automatically generated by tools/generate_kernels.py (Phase 4: SymPy code
// generation).  Do not edit by hand; edit tools/sympy_system.py and regenerate.
//
// Residual (rhs_vars) and Jacobian (csr_vars) kernels for the axisymmetric
// Einstein--Klein--Gordon system of ROTBOSON.  The system and its Jacobian are
// re-derived in SymPy (tools/sympy_system.py) and cross-checked against the
// original Mathematica codegen notebook.
"""


def emit_csr_vars_h() -> str:
    decls = []
    decls.append("void jacobian_2nd_order_variable_omega_cc(")
    decls.append("\tdouble *aa, MKL_INT *ia, MKL_INT *ja,")
    decls.append(
        "\tconst MKL_INT NrTotal, const MKL_INT NzTotal, const MKL_INT dim, const MKL_INT ghost,"
    )
    decls.append("\tconst MKL_INT i, const MKL_INT j, const double dr, const double dz,")
    decls.append("\tconst MKL_INT l, const double m, const double xi,")
    for g in range(1, 7):
        decls.append(
            "\t" + ", ".join(f"const double u{g}{k}" for k in ["01", "10", "11", "12", "21"]) + ","
        )
    decls.append("\tconst MKL_INT offset1, const MKL_INT offset2, const MKL_INT offset3,")
    decls.append("\tconst MKL_INT offset4, const MKL_INT offset5, const MKL_INT offset6);")
    for name, st in STENCILS_4TH.items():
        dr_min = min(p[0][0] for p in st["points"])
        dz_min = min(p[0][1] for p in st["points"])
        decls.append("")
        decls.append(f"void jacobian_4th_order_variable_omega_{name}(")
        decls.append("\tdouble *aa, MKL_INT *ia, MKL_INT *ja,")
        decls.append(
            "\tconst MKL_INT NrTotal, const MKL_INT NzTotal, "
            "const MKL_INT dim, const MKL_INT ghost,"
        )
        decls.append("\tconst MKL_INT i, const MKL_INT j, const double dr, const double dz,")
        decls.append("\tconst MKL_INT l, const double m, const double xi,")
        for g in range(1, 7):
            params = [
                _param_name(g, dr_off, dz_off, dr_min, dz_min)
                for (dr_off, dz_off), _ in st["points"]
            ]
            decls.append("\t" + ", ".join(f"const double {p}" for p in params) + ",")
        decls.append("\tconst MKL_INT offset1, const MKL_INT offset2, const MKL_INT offset3,")
        decls.append("\tconst MKL_INT offset4, const MKL_INT offset5, const MKL_INT offset6);")
    return _HEADER + '#include "tools.h"\n#include "omega_calc.h"\n\n' + "\n".join(decls) + "\n"


def emit_csr_vars_c(jac_str) -> str:
    parts = [_HEADER]
    parts.append('#include "tools.h"\n#include "omega_calc.h"\n')
    parts.append("// Regularization coefficients.\n#define Q1 1.0\n#define Q2 1.0\n")
    parts.append(
        "// Number of grid variables (lapse, shift, h, a, scalar field, regularization).\n#define GNUM 6\n"
    )
    parts.append("")
    parts.append("// Finite-difference stencil coefficients for 2nd order (Fornberg weights).")
    for k, v in FD_2ND.items():
        parts.append(f"#define {k} ({v})")
    parts.append("")
    parts.append(
        _function_body("jacobian_2nd_order_variable_omega_cc", STENCILS_2ND["cc"], jac_str)
    )
    parts.append("")
    parts.append("// Finite-difference stencil coefficients for 4th order (Fornberg weights).")
    for k, v in FD_4TH.items():
        parts.append(f"#define {k} ({v})")
    for name in ("cc", "cs", "sc", "ss"):
        parts.append("")
        parts.append(
            _function_body(f"jacobian_4th_order_variable_omega_{name}", STENCILS_4TH[name], jac_str)
        )
    parts.append("")
    return "\n".join(parts)


def emit_rhs_vars_c() -> str:
    s, R = ss.rhs_residuals()

    used_syms = set().union(*(Ri.free_symbols for Ri in R))
    used_syms = {str(x) for x in used_syms}

    # Physical-derivative fetch, one symbol per grid function (only those
    # actually referenced by the residual brackets).
    def dline(var, k):
        arr = {"Dr": "Dr_u", "Dz": "Dz_u", "Drr": "Drr_u", "Dzz": "Dzz_u"}[var]
        return f"\tdouble {var}_u{k} = {arr}[{k} * dim + IDX(i, j)];"

    lines = [_HEADER]
    lines.append('#include "tools.h"\n#include "omega_calc.h"\n')
    lines.append("// Regularization coefficients (auxiliary terms in the lambda equation).")
    lines.append("#define Q1 1.0")
    lines.append("#define Q2 1.0")
    lines.append("")
    lines.append("void rhs_vars(")
    lines.append("\tdouble *f, double *u, double *Dr_u, double *Dz_u,")
    lines.append("\tdouble *Drr_u, double *Dzz_u,")
    lines.append(
        "\tconst MKL_INT NrTotal, const MKL_INT NzTotal, const MKL_INT dim, const MKL_INT ghost,"
    )
    lines.append("\tconst MKL_INT i, const MKL_INT j, const double dr, const double dz,")
    lines.append("\tconst MKL_INT l, const double m, const double w, const double rescale,")
    lines.append("\tdouble *u_aux, double *Dr_u_aux)")
    lines.append("{")
    lines.append("\t(void)NrTotal; (void)u_aux;")
    lines.append("")
    lines.append("\t// Grid values (u0=log alpha, u1=beta, u2=log h, u3=log a, u4=psi, u5=lambda).")
    lines.append("\tdouble l_alpha = u[0 * dim + IDX(i, j)];")
    lines.append("\tdouble beta    = u[1 * dim + IDX(i, j)];")
    lines.append("\tdouble l_h     = u[2 * dim + IDX(i, j)];")
    lines.append("\tdouble l_a     = u[3 * dim + IDX(i, j)];")
    lines.append("\tdouble psi     = u[4 * dim + IDX(i, j)];")
    lines.append("\tdouble lambda  = u[5 * dim + IDX(i, j)];")
    lines.append("")
    lines.append("\t// Physical derivatives (computed by rhs.c).")
    for var in ("Dr", "Dz", "Drr", "Dzz"):
        for k in range(6):
            if f"{var}_u{k}" in used_syms:
                lines.append(dline(var, k))
    lines.append("")
    lines.append("\t// Regularization auxiliary radial derivatives.")
    lines.append("\tdouble Dr_u6 = Dr_u_aux[0 * dim + IDX(i, j)];")
    lines.append("\tdouble Dr_u7 = Dr_u_aux[1 * dim + IDX(i, j)];")
    lines.append("")
    lines.append("\t// Coordinates.")
    lines.append("\tdouble r = dr * (i + 0.5 - ghost);")
    lines.append("\tdouble r2 = r * r;")
    lines.append("\tdouble rlm1 = (l == 1) ? 1.0 : pow(r, l - 1);")
    lines.append("\tdouble rl = rlm1 * r;")
    lines.append("\tdouble dzodr = dz / dr;")
    lines.append("")
    lines.append("\t// Physical short-hands.")
    lines.append("\tdouble alpha = exp(l_alpha);")
    lines.append("\tdouble alpha2 = alpha * alpha;")
    lines.append("\tdouble h = exp(l_h);")
    lines.append("\tdouble h2 = h * h;")
    lines.append("\tdouble a = exp(l_a);")
    lines.append("\tdouble a2 = a * a;")
    lines.append("\tdouble m2 = m * m;")
    lines.append("\tdouble wplOmega = w + l * beta;")
    lines.append("\tdouble phi = rl * psi;")
    lines.append("\tdouble phior = rlm1 * psi;")
    lines.append("\tdouble phi2 = phi * phi;")
    lines.append("\tdouble phi2or2 = phior * phior;")
    lines.append("")
    lines.append("\t// The lambda equation re-defines a2 in terms of the regularization variable.")
    lines.append("\tdouble a2_r = h2 + r2 * lambda;")
    lines.append("")
    lines.append("\t// Residual brackets (rescale = -1 from the driver).")
    labels = ["log alpha", "beta", "log h", "log a", "psi", "lambda"]
    for k, Ri in enumerate(R):
        expr = sp.ccode(Ri)
        lines.append(f"\t// u{k} = {labels[k]}.")
        lines.append(f"\tf[{k} * dim + IDX(i, j)] = rescale * (dr * dr * dzodr * ({expr}));")
    lines.append("")
    lines.append("\treturn;")
    lines.append("}")
    lines.append("")
    lines.append(_RHS_BDRY)
    return "\n".join(lines) + "\n"


_RHS_BDRY = """void rhs_bdry(
\tdouble *f,
\tdouble *u,
\tdouble *Dr_u,
\tdouble *Dz_u,
\tconst MKL_INT NrTotal,
\tconst MKL_INT NzTotal,
\tconst MKL_INT dim,
\tconst MKL_INT ghost,
\tconst MKL_INT i,
\tconst MKL_INT j,
\tconst double dr,
\tconst double dz,
\tconst MKL_INT l,
\tconst double m,
\tconst double w,
\tconst double M,
\tconst double J,
\tconst double rescale
)
{
\t(void)NrTotal; (void)M; (void)J;

\t// Coordinates.
\tdouble r = dr * (i + 0.5 - ghost);
\tdouble z = dz * (j + 0.5 - ghost);
\tdouble rr2 = r * r + z * z;
\tdouble rr = sqrt(rr2);
\tdouble scale = dr * dz / rr2;

\t// Scalar field mass and decay constant.
\tdouble m2 = m * m;
\tdouble chi = sqrt(m2 - w * w);

\t// Fetch values.
\tdouble l_alpha    = u[IDX(i, j)];
\tdouble Dr_l_alpha = Dr_u[IDX(i, j)];
\tdouble Dz_l_alpha = Dz_u[IDX(i, j)];
\tdouble beta       = u[dim + IDX(i, j)];
\tdouble Dr_beta    = Dr_u[dim + IDX(i, j)];
\tdouble Dz_beta    = Dz_u[dim + IDX(i, j)];
\tdouble l_h        = u[2 * dim + IDX(i, j)];
\tdouble Dr_l_h     = Dr_u[2 * dim + IDX(i, j)];
\tdouble Dz_l_h     = Dz_u[2 * dim + IDX(i, j)];
\tdouble l_a        = u[3 * dim + IDX(i, j)];
\tdouble Dr_l_a     = Dr_u[3 * dim + IDX(i, j)];
\tdouble Dz_l_a     = Dz_u[3 * dim + IDX(i, j)];
\tdouble psi        = u[4 * dim + IDX(i, j)];
\tdouble Dr_psi     = Dr_u[4 * dim + IDX(i, j)];
\tdouble Dz_psi     = Dz_u[4 * dim + IDX(i, j)];
\tdouble lambda     = u[5 * dim + IDX(i, j)];
\tdouble Dr_lambda  = Dr_u[5 * dim + IDX(i, j)];
\tdouble Dz_lambda  = Dz_u[5 * dim + IDX(i, j)];

\t// Robin and exponential-decay boundary conditions.
\tf[IDX(i, j)] = rescale * scale * (r * Dr_l_alpha + z * Dz_l_alpha + l_alpha);

\tf[dim + IDX(i, j)] = rescale * scale * (r * Dr_beta + z * Dz_beta + 3.0 * beta);

\tf[2 * dim + IDX(i, j)] = rescale * scale * (r * Dr_l_h + z * Dz_l_h + l_h);

\tf[3 * dim + IDX(i, j)] = rescale * scale * (r * Dr_l_a + z * Dz_l_a + l_a);

\tf[4 * dim + IDX(i, j)] = rescale * scale * (r * Dr_psi + z * Dz_psi + (rr * chi + l + 1.0) * psi);

\tf[5 * dim + IDX(i, j)] = rescale * scale * (r * Dr_lambda + z * Dz_lambda + 4.0 * lambda);

\treturn;
}"""


def emit_rhs_vars_h() -> str:
    return (
        _HEADER
        + """
void rhs_vars(double *f, double *u, double *Dr_u, double *Dz_u,
\tdouble *Drr_u, double *Dzz_u,
\tconst MKL_INT NrTotal, const MKL_INT NzTotal, const MKL_INT dim,
\tconst MKL_INT ghost, const MKL_INT i, const MKL_INT j,
\tconst double dr, const double dz, const MKL_INT l, const double m,
\tconst double w, const double rescale, double *u_aux, double *Dr_u_aux);

void rhs_bdry(double *f, double *u, double *Dr_u, double *Dz_u,
\tconst MKL_INT NrTotal, const MKL_INT NzTotal, const MKL_INT dim,
\tconst MKL_INT ghost, const MKL_INT i, const MKL_INT j,
\tconst double dr, const double dz, const MKL_INT l, const double m,
\tconst double w, const double M, const double J, const double rescale);
"""
    )


def _clang_format(content: str, filename: str, repo: Path) -> str:
    """Pipe generated C through clang-format (repo .clang-format style).

    The checked-in kernels are stored clang-format-clean; running the formatter
    here keeps the generator idempotent with respect to a repo-wide
    clang-format pass.  If clang-format is unavailable the raw text is returned
    unchanged (the idempotency check will then simply compare raw text).
    """
    if shutil.which("clang-format") is None:
        return content
    proc = subprocess.run(
        ["clang-format", "--style=file", f"--assume-filename={filename}"],
        input=content,
        text=True,
        capture_output=True,
        cwd=repo,
    )
    return proc.stdout if proc.returncode == 0 else content


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check", action="store_true", help="exit non-zero if regenerated files differ from src/"
    )
    ap.add_argument("--out-dir", type=Path, default=None)
    args = ap.parse_args()

    s, R, f, Jc = ss.build_c()
    jac_str = _expr_strings(Jc)

    repo = Path(__file__).resolve().parent.parent

    files = {
        "src/csr_vars.c": emit_csr_vars_c(jac_str),
        "src/csr_vars.h": emit_csr_vars_h(),
        "src/rhs_vars.c": emit_rhs_vars_c(),
        "src/rhs_vars.h": emit_rhs_vars_h(),
    }

    changed = False
    for rel, content in files.items():
        content = _clang_format(content, rel, repo)
        target = repo / rel
        if args.check:
            if not target.exists() or target.read_text() != content:
                print(f"[generate_kernels] DIFFERS: {rel}")
                changed = True
        else:
            target.write_text(content)
            print(f"[generate_kernels] wrote {rel} ({len(content)} bytes)")
    if args.check:
        print("[generate_kernels] check " + ("FAILED" if changed else "OK"))
        return 1 if changed else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
