void csr_grid_fill_4th(
	csr_matrix A,
	const MKL_INT NrInterior,
	const MKL_INT NzInterior,
	const double dr, 
	const double dz,
	double *u,
	const MKL_INT l,
	const double m,
	const MKL_INT r_sym[GNUM],
	const MKL_INT z_sym[GNUM],
	const MKL_INT bound_order[GNUM],
	const MKL_INT nnz[GNUM],
	const MKL_INT p_cc[GNUM],
	const MKL_INT p_cs[GNUM],
	const MKL_INT p_sc[GNUM],
	const MKL_INT p_ss[GNUM],
	const MKL_INT p_bound[GNUM],
	void (*j_cc)(double *, MKL_INT *, MKL_INT *,
		const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT,
		const MKL_INT, const MKL_INT, const double, const double,
		const MKL_INT, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT),
	void (*j_cs)(double *, MKL_INT *, MKL_INT *,
		const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT,
		const MKL_INT, const MKL_INT, const double, const double,
		const MKL_INT, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT),
	void (*j_sc)(double *, MKL_INT *, MKL_INT *,
		const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT,
		const MKL_INT, const MKL_INT, const double, const double,
		const MKL_INT, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT),
	void (*j_ss)(double *, MKL_INT *, MKL_INT *,
		const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT,
		const MKL_INT, const MKL_INT, const double, const double,
		const MKL_INT, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double, const double, const double, const double, const double, const double, const double,
		const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT));

void csr_grid_fill_2nd(
	csr_matrix A,
	const MKL_INT NrInterior, 
	const MKL_INT NzInterior, 
	const double dr, 
	const double dz,
	double *u,
	const MKL_INT l,
	const double m,
	const MKL_INT r_sym[GNUM],
	const MKL_INT z_sym[GNUM],
	const MKL_INT bound_order[GNUM],
	const MKL_INT nnz[GNUM],
	const MKL_INT p_center[GNUM],
	const MKL_INT p_bound[GNUM],
	void (*j_cc)(double *, MKL_INT *, MKL_INT *,
		const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT,
		const double, const double, const MKL_INT, const double, const double,
		const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double,
		const double, const double, const double, const double, const double,
		const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT, const MKL_INT));