void initial_interpolator(double *u_1,
	double *u_0,
	const MKL_INT NrInterior_0,
	const MKL_INT NzInterior_0,
	const MKL_INT ghost_0,
	const MKL_INT order_0,
	const double dr_0, 
	const double dz_0,
	const MKL_INT NrInterior_1,
	const MKL_INT NzInterior_1,
	const MKL_INT ghost_1,
	const MKL_INT order_1,
	const double dr_1, 
	const double dz_1,
	const double w,
	const double m,
	const MKL_INT l);