void regularization_calc(double *lambda,
	const MKL_INT i_max,
	double *u, 
	double *Dr_u,
	double *Dz_u, 
	double *Drr_u, 
	double *Dzz_u,
	const double dr, const double dz,
	const MKL_INT NrTotal, const MKL_INT NzTotal, const MKL_INT dim,
	const MKL_INT ghost, const MKL_INT order,
	const double w, const double m, const MKL_INT l);