// Automatically generated by tools/generate_kernels.py (Phase 4: SymPy code
// generation).  Do not edit by hand; edit tools/sympy_system.py and regenerate.
//
// Residual (rhs_vars) and Jacobian (csr_vars) kernels for the axisymmetric
// Einstein--Klein--Gordon system of ROTBOSON.  The system and its Jacobian are
// re-derived in SymPy (tools/sympy_system.py) and cross-checked against the
// original Mathematica codegen notebook.

void rhs_vars(double *f, double *u, double *Dr_u, double *Dz_u,
	double *Drr_u, double *Dzz_u,
	const MKL_INT NrTotal, const MKL_INT NzTotal, const MKL_INT dim,
	const MKL_INT ghost, const MKL_INT i, const MKL_INT j,
	const double dr, const double dz, const MKL_INT l, const double m,
	const double w, const double rescale, double *u_aux, double *Dr_u_aux);

void rhs_bdry(double *f, double *u, double *Dr_u, double *Dz_u,
	const MKL_INT NrTotal, const MKL_INT NzTotal, const MKL_INT dim,
	const MKL_INT ghost, const MKL_INT i, const MKL_INT j,
	const double dr, const double dz, const MKL_INT l, const double m,
	const double w, const double M, const double J, const double rescale);
