#!/bin/bash
#
# Name of job.
#PBS -N l=3,ROTBOSON
#
# Output files.
#PBS -o $PBS_JOBNAME.$PBS_JOBID.out
#PBS -e $PBS_JOBNAME.$PBS_JOBID.err
#
# Set to "short" queue.
#PBS -q short
#
# Resources.
#PBS -l nodes=1:ppn=54
#PBS -l mem=24gb
#PBS -l vmem=28gb
#
# Walltime
#PBS -l walltime=01:00:00
#
# Email notifications.
#PBS -m abe -M santiago.ontanon@correo.nucleares.unam.mx

# Change to current directory.
cd $PBS_O_WORKDIR

# Send email indication job start.
echo -e "Subject: $PBS_JOBNAME.$PBS_JOBID \n\nExecution has begun." | sendmail santiago.ontanon@correo.nucleares.unam.mx

# Job information.
echo ==================================
echo Executing on : `hostname`
echo Data: `date`
echo Directory: `pwd`
echo Assigned Resources:
echo	`cat $PBS_NODEFILE`
NPROCS=`wc -l < $PBS_NODEFILE`
echo Total: $NPROCS cpus
echo ==================================
cat $PBS_NODEFILE > $HOME/nodos
echo ==================================
echo	Output...
echo ==================================

# Set OMP_NUM_THREADS
export OMP_NUM_THREADS=$PBS_NUM_PPN
export MKL_NUM_THREADS=$PBS_NUM_PPN

# MKL OOC
export MKL_PARDISO_OOC_PATH=/storage/icn/sontanon/ROTBOSON/ooc
export MKL_PARDISO_OOC_MAX_CORE_SIZE=150000
export MKL_PARDISO_OOC_MAX_SWAP_SIZE=10000
export MKL_PARDISO_OOC_KEEP_FILE=1

time /storage/icn/sontanon/ROTBOSON/out/StandarizedOutput/ROTBOSON "/storage/icn/sontanon/ROTBOSON/out/StandarizedOutput/l=3,w=X.XXXXXE-01,dr=8.00000E-02,N=0400.par"
echo -e "Subject: $PBS_JOBNAME.$PBS_JOBID \n\nRun has finished." | sendmail santiago.ontanon@correo.nucleares.unam.mx
